var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};
$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,d){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(c){d||(d=!0,a.call(b,c))}}var b=this,d=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(l){d.reject(l)}};e.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(r){m(r)}}:b}var c,m,p=new e(function(a,b){c=a;m=b});this.callWhenSettled_(d(a,c),d(b,m));return p};
e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?f.asyncExecute(d):this.onSettledCallbacks_.push(d)};e.resolve=c;e.reject=function(a){return new e(function(b,d){d(a)})};e.race=function(a){return new e(function(b,d){for(var e=$jscomp.makeIterator(a),k=e.next();!k.done;k=e.next())c(k.value).callWhenSettled_(b,
d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function k(b){return function(d){l[b]=d;m--;0==m&&a(l)}}var l=[],m=0;do l.push(void 0),m++,c(d.value).callWhenSettled_(k(l.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var c=a.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(c.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var e=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var g=0;g<f&&c<e;)if(b[c++]!=a[g++])return!1;return g>=f}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,c,d){c=null!=c?c:function(a){return a};var b=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof f){a=f.call(a);for(var g=0;!(f=a.next()).done;)b.push(c.call(d,f.value,g++))}else for(f=a.length,g=0;g<f;g++)b.push(c.call(d,a[g],g));return b}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(c,d,e){return c==a&&"q"==d&&e==b}}));return!0===b.q}catch(c){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),d=Object.seal({}),c=new a([[b,2],[d,3]]);if(2!=c.get(b)||3!=c.get(d))return!1;c.delete(b);c.set(d,4);return!c.has(b)&&4==c.get(d)}catch(q){return!1}}function c(){}function d(a){var b=typeof a;return"object"===b&&null!==a||"function"===b}function e(a){if(!$jscomp.owns(a,g)){var b=new c;$jscomp.defineProperty(a,g,{value:b})}}function f(a){var b=Object[a];b&&(Object[a]=function(a){if(a instanceof
c)return a;e(a);return b(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0,k=function(a){this.id_=(h+=Math.random()+1).toString();if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};k.prototype.set=function(a,b){if(!d(a))throw Error("Invalid WeakMap key");e(a);if(!$jscomp.owns(a,g))throw Error("WeakMap key fail: "+
a);a[g][this.id_]=b;return this};k.prototype.get=function(a){return d(a)&&$jscomp.owns(a,g)?a[g][this.id_]:void 0};k.prototype.has=function(a){return d(a)&&$jscomp.owns(a,g)&&$jscomp.owns(a[g],this.id_)};k.prototype.delete=function(a){return d(a)&&$jscomp.owns(a,g)&&$jscomp.owns(a[g],this.id_)?delete a[g][this.id_]:!1};return k},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a($jscomp.makeIterator([[b,"s"]]));if("s"!=d.get(b)||1!=d.size||d.get({x:4})||d.set({x:4},"t")!=d||2!=d.size)return!1;var c=d.entries(),e=c.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=c.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!c.next().done?!1:!0}catch(q){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var c=new WeakMap,d=function(a){this.data_={};this.head_=g();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};d.prototype.set=function(a,b){a=0===a?0:a;var d=e(this,a);d.list||(d.list=this.data_[d.id]=[]);d.entry?d.entry.value=b:(d.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:a,
value:b},d.list.push(d.entry),this.head_.previous.next=d.entry,this.head_.previous=d.entry,this.size++);return this};d.prototype.delete=function(a){a=e(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};d.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=g();this.size=0};d.prototype.has=function(a){return!!e(this,a).entry};
d.prototype.get=function(a){return(a=e(this,a).entry)&&a.value};d.prototype.entries=function(){return f(this,function(a){return[a.key,a.value]})};d.prototype.keys=function(){return f(this,function(a){return a.key})};d.prototype.values=function(){return f(this,function(a){return a.value})};d.prototype.forEach=function(a,b){for(var d=this.entries(),c;!(c=d.next()).done;)c=c.value,a.call(b,c[1],c[0],this)};d.prototype[Symbol.iterator]=d.prototype.entries;var e=function(a,b){var d=b&&typeof b;"object"==
d||"function"==d?c.has(b)?d=c.get(b):(d=""+ ++h,c.set(b,d)):d="p_"+b;var e=a.data_[d];if(e&&$jscomp.owns(a.data_,d))for(a=0;a<e.length;a++){var f=e[a];if(b!==b&&f.key!==f.key||b===f.key)return{id:d,list:e,index:a,entry:f}}return{id:d,list:e,index:-1,entry:void 0}},f=function(a,b){var d=a.head_;return $jscomp.iteratorPrototype(function(){if(d){for(;d.head!=a.head_;)d=d.previous;for(;d.next!=d.head;)return d=d.next,{done:!1,value:b(d)};d=null}return{done:!0,value:void 0}})},g=function(){var a={};return a.previous=
a.next=a.head=a},h=0;return d},"es6","es3");$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,c){return c})}},"es8","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a($jscomp.makeIterator([b]));if(!c.has(b)||1!=c.size||c.add(b)!=c||1!=c.size||c.add({x:4})!=c||2!=c.size)return!1;var f=c.entries(),g=f.next();if(g.done||g.value[0]!=b||g.value[1]!=b)return!1;g=f.next();return g.done||g.value[0]==b||4!=g.value[0].x||g.value[1]!=g.value[0]?!1:f.next().done}catch(h){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbolIterator();var c=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};c.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};c.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};c.prototype.clear=function(){this.map_.clear();
this.size=0};c.prototype.has=function(a){return this.map_.has(a)};c.prototype.entries=function(){return this.map_.entries()};c.prototype.values=function(){return this.map_.values()};c.prototype.keys=c.prototype.values;c.prototype[Symbol.iterator]=c.prototype.values;c.prototype.forEach=function(a,b){var d=this;this.map_.forEach(function(c){return a.call(b,c,c,d)})};return c},"es6","es3");
$jscomp.polyfill("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push(a[d]);return b}},"es8","es3");$jscomp.polyfill("Object.entries",function(a){return a?a:function(a){var b=[],d;for(d in a)$jscomp.owns(a,d)&&b.push([d,a[d]]);return b}},"es8","es3");
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var b=$jscomp.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}},"es6","es3");$jscomp.stringPadding=function(a,b){a=void 0!==a?String(a):" ";return 0<b&&a?a.repeat(Math.ceil(b/a.length)).substring(0,b):""};
$jscomp.polyfill("String.prototype.padStart",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,null,"padStart");return $jscomp.stringPadding(c,a-b.length)+b}},"es8","es3");var SUPABASE_URL="https://iglmqwpagzjadwauvchh.supabase.co",SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnbG1xd3BhZ3pqYWR3YXV2Y2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODk4NDAsImV4cCI6MjA2NjQ2NTg0MH0.Mtiwp31mJvbLRTotbrb4_DobjjpM4kg9f4-G8oWz85E",supabaseClient,flatpickrInstance;
console.time("start");try{(supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY))&&console.log("Supabase客户端初始化成功")}catch(a){showRoundedAlert("系统初始化失败，请刷新页面或联系管理员","error")}
var dateRangePicker=document.getElementById("dateRangePicker"),queryBtn=document.getElementById("queryBtn"),clearBtn=document.getElementById("clearBtn"),summaryTable=document.getElementById("summaryTable").querySelector("tbody"),detailTable=document.getElementById("detailTable").querySelector("tbody"),loadingEl=document.getElementById("loading"),totalQuantityEl=document.getElementById("totalQuantity"),totalAmountEl=document.getElementById("totalAmount"),totalProductsEl=document.getElementById("totalProducts"),
totalBrandsEl=document.getElementById("totalBrands"),toggleDetails=document.getElementById("toggleDetails"),detailSection=document.getElementById("detailSection"),totalProfitEl=document.getElementById("totalProfit"),switchWarehouseBtn=document.getElementById("switchWarehouseBtn"),warehouseSelector=document.getElementById("warehouseSelector"),warehouseOptions=document.getElementById("warehouseOptions"),brandSelector=document.getElementById("brandSelector"),brandOptions=document.getElementById("brandOptions"),
productSelector=document.getElementById("productSelector"),productOptions=document.getElementById("productOptions"),customerSelector=document.getElementById("customerSelector"),customerOptions=document.getElementById("customerOptions"),authContainer=document.getElementById("authContainer"),appContainer=document.getElementById("appContainer"),loginForm=document.getElementById("loginForm"),registerForm=document.getElementById("registerForm"),loginEmail=document.getElementById("loginEmail"),loginPassword=
document.getElementById("loginPassword"),registerEmail=document.getElementById("registerEmail"),registerPassword=document.getElementById("registerPassword"),registerPhone=document.getElementById("registerPhone"),loginBtn=document.getElementById("loginBtn"),registerBtn=document.getElementById("registerBtn"),forgotPasswordLink=document.getElementById("forgotPasswordLink"),authTabs=document.querySelectorAll(".auth-tab"),userStatus=document.getElementById("userStatus"),userInfo=document.getElementById("userInfo"),
userName=document.getElementById("userName"),userMenu=document.getElementById("userMenu"),logoutBtn=document.getElementById("logoutBtn"),allWarehouses=[],allBrands=[],allProductsData=[],brandMap={},currentOpenDropdown=null,selectedProducts=[],user=null,currentWarehouse="default",allSalesPersons=[],allCustomers=[],salesRecords=[],startDateStr="",endDateStr="";function formatNumber(a){return"number"!==typeof a?"0":a.toLocaleString("zh-CN",{minimumFractionDigits:0,maximumFractionDigits:2})}
function setDefaultDates(){var a=new Date,b=new Date;1===a.getDate()?(b.setMonth(b.getMonth()-1),b.setDate(1),a.setMonth(a.getMonth()-1),a.setDate((new Date(a.getFullYear(),a.getMonth()+1,0)).getDate())):(b.setDate(1),a.setDate(a.getDate()-1));flatpickrInstance.setDate([b,a])}
function initAuth(){var a,b,c,d,e,f,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){if(1==h.nextAddress){if(!supabaseClient)return h.return(!1);h.setCatchFinallyBlocks(2);return h.yield(supabaseClient.auth.getUser(),4)}if(2!=h.nextAddress){a=h.yieldResult;b=a.data;if(c=b.user)return user=c,d=c.email.split("@")[0],e={162004332:"系统管理员",rickyone:"数据管理员",13762405681:"王英",ksf2025:"康师傅",pepsi_cola:"百事可乐",coca_cola:"可口可乐",15096086678:"娟子"},f=e[d]||d,userName.textContent=f,userStatus.style.display=
"block",authContainer.style.display="none",appContainer.style.display="block",showRoundedAlert("欢迎"+f+"！","success"),h.return(!0);userStatus.style.display="none";authContainer.style.display="block";return h.return(!1)}g=h.enterCatchBlock();showRoundedAlert("用户认证发生错误:",g);return h.return(!1)})}
function showRoundedAlert(a,b){b=void 0===b?"error":b;var c=document.getElementById("custom-alert");c&&c.remove();var d=document.createElement("div");d.id="custom-alert";d.className="rounded-alert "+b;d.innerHTML='\n    <div class="alert-content">\n      <i class="fas fa-'+("error"===b?"exclamation-circle":"check-circle")+'"></i>\n      <span>'+a+"</span>\n    </div>\n  ";document.body.appendChild(d);a=(window.innerWidth-d.offsetWidth)/2;d.style.top="20px";d.style.left=a+"px";setTimeout(function(){d.classList.add("fade-out");
setTimeout(function(){return d.remove()},300)},2E3)}
function switchWarehouse(){detailSection.classList.contains("visible")&&(detailSection.classList.remove("visible"),document.querySelector("#toggleDetails i").classList.replace("fa-chevron-up","fa-chevron-down"));currentWarehouse="default"===currentWarehouse?"longqiao":"default";var a=document.querySelector(".filters-row");"longqiao"===currentWarehouse?a.classList.add("longqiao"):a.classList.remove("longqiao");updateUIForWarehouse();clearPieChart();setDefaultDates();loadFilterOptions().then(function(){warehouseMultiSelect.reset();
brandMultiSelect.reset();productMultiSelect.reset();customerMultiSelect&&customerMultiSelect.reset();updateDetailTableHeader();loadData()})}
function updateUIForWarehouse(){var a=document.querySelector("header h1"),b=document.getElementById("profitCard");"longqiao"===currentWarehouse?(a.innerHTML='<img src="icon64.png" alt="应用图标" style="border-radius: 8px; filter: drop-shadow(0px 2px 4px rgba(0, 0, 0, 0.5));"> 隆桥仓库销售数据查询系统',document.querySelector(".filter-group label:has(i.fas.fa-warehouse)").innerHTML='<i class="fas fa-user"></i> 销售人员',b.style.display="block"):(a.innerHTML='<img src="icon64.png" alt="应用图标" style="border-radius: 8px; filter: drop-shadow(0px 2px 4px rgba(0, 0, 0, 0.5));"> 多多买菜销售数据查询系统',
document.querySelector(".filter-group label:has(i.fas.fa-user)").innerHTML='<i class="fas fa-warehouse"></i> 仓库',b.style.display="none");if(a=document.getElementById("customerFilterGroup"))a.style.display="longqiao"===currentWarehouse?"block":"none"}
function updateDetailTableHeader(){var a=document.querySelector("#detailTable thead"),b="\n    <tr>\n      <th>日期</th>\n      <th>"+("longqiao"===currentWarehouse?"客户名称":"商品ID")+"</th> \n      <th>商品名称</th>\n      <th>品牌</th>\n      <th>"+("longqiao"===currentWarehouse?"销售人员":"仓库")+"</th>\n      <th>销量</th>\n      <th>"+("longqiao"===currentWarehouse?"成本":"单价")+"</th>\n      <th>金额</th>\n  ";"longqiao"===currentWarehouse&&(b+="<th>毛利</th>");a.innerHTML=b+"</tr>"}
var MultiSelect=function(a,b,c){this.selector=a;this.optionsContainer=b;this.placeholder=c;this.selectedValues=[];this.allOptions=[];this.clearBtn=a.querySelector(".clear-btn");this.initEvents()};
MultiSelect.prototype.initEvents=function(){var a=this;this.selector.addEventListener("click",function(b){return a.toggleDropdown(b)});this.clearBtn.addEventListener("click",function(b){return a.clearSelection(b)});this.optionsContainer.addEventListener("change",function(b){return a.handleOptionChange(b)});this.optionsContainer.addEventListener("mouseenter",function(){return a.optionsContainer.classList.add("active")});this.optionsContainer.addEventListener("mouseleave",function(){return a.optionsContainer.classList.remove("active")})};
MultiSelect.prototype.toggleDropdown=function(a){a.target.classList.contains("tag-remove")||a.target.classList.contains("tag")||a.target.closest(".tag-remove")||a.target.closest(".tag")||(a.stopPropagation(),closeAllDropdowns(),this.optionsContainer.classList.contains("visible")||(this.optionsContainer.classList.add("visible"),currentOpenDropdown=this.optionsContainer,this.selector.querySelector(".arrow").classList.replace("fa-chevron-down","fa-chevron-up"),this.positionDropdown()))};
MultiSelect.prototype.positionDropdown=function(){var a=this.selector.getBoundingClientRect(),b=this.selector.parentElement.getBoundingClientRect();this.optionsContainer.style.width=a.width+"px";this.optionsContainer.style.left=a.left-b.left+"px";this.optionsContainer.style.top=a.bottom-b.top+"px"};
MultiSelect.prototype.clearSelection=function(a){a.stopPropagation();this.selectedValues=[];this.updateDisplay();this.optionsContainer.querySelectorAll('input[type="checkbox"]').forEach(function(a){return a.checked=!1});"brandSelector"===this.selector.id?(selectedProducts=[],filterProductsByBrand()):"productSelector"===this.selector.id&&(selectedProducts=[],filterProductsByBrand())};
MultiSelect.prototype.handleOptionChange=function(a){if(a.target.matches('input[type="checkbox"]')){a=a.target;var b=a.value;a.id.startsWith("selectAll")?(b=this.optionsContainer.querySelectorAll('input[type="checkbox"]:not([id="'+a.id+'"])'),a.checked?(this.selectedValues=this.allOptions.map(function(a){return a.value}),b.forEach(function(a){return a.checked=!0})):(this.selectedValues=[],b.forEach(function(a){return a.checked=!1}))):(a.checked?this.selectedValues.includes(b)||this.selectedValues.push(b):
(a=this.selectedValues.indexOf(b),-1<a&&this.selectedValues.splice(a,1)),this.updateSelectAllState());this.updateDisplay();"brandSelector"===this.selector.id&&(selectedProducts=[],filterProductsByBrand(),"longqiao"===currentWarehouse&&filterCustomersByBrand());"warehouseSelector"===this.selector.id&&reloadBrandAndProductOptions()}};
MultiSelect.prototype.updateDisplay=function(){var a=this,b=this.selector.querySelector(".placeholder"),c=this.selector.querySelector(".selected-display"),d=this.selector.querySelector(".arrow");c.innerHTML="";if(0===this.selectedValues.length)b.textContent="全部"+this.placeholder,b.style.display="block",c.style.display="none",d.style.display="block",d.classList.replace("fa-times","fa-chevron-down"),this.clearBtn.style.display="none";else{b.style.display="none";c.style.display="flex";b=this.selectedValues.slice(0,
5);var e=this.selectedValues.length-5;b.forEach(function(b){var d=a.allOptions.find(function(a){return a.value===b});d&&c.insertAdjacentHTML("beforeend","\n        <div class='tag' data-value='"+b+"'>\n          "+d.label+"\n          <span class='tag-remove'><i class=\"far fa-circle-xmark\"></i></span> \n        </div>\n      ")});0<e&&(b=document.createElement("div"),b.className="tag more-tag",b.textContent="...等"+this.selectedValues.length+"项",c.appendChild(b));d.style.display="none";this.clearBtn.style.display=
"block"}};MultiSelect.prototype.reset=function(){this.selectedValues=[];this.updateDisplay();this.optionsContainer.querySelectorAll('input[type="checkbox"]').forEach(function(a){return a.checked=!1})};MultiSelect.prototype.updateSelectAllState=function(){var a=this.optionsContainer.querySelector('input[id^="selectAll"]');if(a){var b=this.optionsContainer.querySelectorAll('input[type="checkbox"]:not([id^="selectAll"])');a.checked=0<b.length&&Array.from(b).every(function(a){return a.checked})}};
MultiSelect.prototype.setOptions=function(a){this.allOptions=a;this.renderOptions();this.updateDisplay()};
MultiSelect.prototype.renderOptions=function(){var a=this;this.optionsContainer.innerHTML="";var b=document.createElement("div");b.className="option";b.innerHTML='\n      <input type="checkbox" id="selectAll'+this.selector.id+'">\n      <label for="selectAll'+this.selector.id+'">全选</label>\n    ';this.optionsContainer.appendChild(b);this.allOptions.forEach(function(b){var d=document.createElement("div");d.className="option";d.innerHTML='\n        <input type="checkbox" id="'+a.selector.id+"-"+b.value+
'" \n              value="'+b.value+'" '+(a.selectedValues.includes(b.value)?"checked":"")+'>\n        <label for="'+a.selector.id+"-"+b.value+'">'+b.label+"</label>\n      ";a.optionsContainer.appendChild(d)})};function closeAllDropdowns(){document.querySelectorAll(".options-container").forEach(function(a){a.classList.remove("visible");(a=a.previousElementSibling.querySelector(".arrow"))&&a.classList.replace("fa-chevron-up","fa-chevron-down")});currentOpenDropdown=null}
var warehouseMultiSelect,brandMultiSelect,productMultiSelect,customerMultiSelect;
function filterProductsByBrand(){productOptions.innerHTML="";var a=document.createElement("div");a.className="option";a.id="productSelectAll";a.innerHTML='\n    <input type="checkbox" id="selectAllProducts">\n    <label for="selectAllProducts">全选</label>\n  ';productOptions.appendChild(a);a=[];var b=brandMultiSelect.selectedValues.length;0<b?a=allProductsData.filter(function(a){return brandMap[a.product_id]&&brandMultiSelect.selectedValues.includes(brandMap[a.product_id])}):(a=allProductsData,b="全部");
productMultiSelect.selectedValues=[];a.forEach(function(a){var b=document.createElement("div");b.className="option";var c=productMultiSelect.selectedValues.includes(a.product_id);b.innerHTML='\n      <input type="checkbox" id="product-'+a.product_id+'" \n             value="'+a.product_id+'" '+(c?"checked":"")+'>\n      <label for="product-'+a.product_id+'">'+a.product_name+"</label>\n    ";productOptions.appendChild(b)});productSelector.querySelector(".placeholder").textContent=0===brandMultiSelect.selectedValues.length?
"全部商品":"已筛选"+b+"个品牌";productMultiSelect.setOptions(a.map(function(a){return{value:a.product_id,label:a.product_name}}).sort(function(a,b){return a.label.localeCompare(b.label)}))}
function filterCustomersByBrand(){var a=brandMultiSelect.selectedValues,b=warehouseMultiSelect.selectedValues,c=[];c=0<a.length||0<b.length?allCustomers.filter(function(d){return salesRecords.some(function(c){return c.customer===d&&(0===a.length||a.includes(c.brand))&&(0===b.length||b.includes(c.sales))})}):allCustomers;customerMultiSelect.setOptions(c.map(function(a){return{value:a,label:a}}).sort(function(a,b){return a.label.localeCompare(b.label)}));customerMultiSelect&&customerMultiSelect.reset()}
function reloadBrandAndProductOptions(){if(salesRecords&&0!==salesRecords.length)try{var a=[].concat($jscomp.arrayFromIterable(salesRecords));"longqiao"===currentWarehouse?0<warehouseMultiSelect.selectedValues.length&&(a=a.filter(function(a){return warehouseMultiSelect.selectedValues.includes(a.sales)})):0<warehouseMultiSelect.selectedValues.length&&(a=a.filter(function(a){return warehouseMultiSelect.selectedValues.includes(a.warehouse)}));var b=new Map;brandMap={};a.forEach(function(a){a.product_id&&
(b.has(a.product_id)||b.set(a.product_id,{product_id:a.product_id,product_name:a.product_name||"未知商品"}),brandMap[a.product_id]=a.brand||"无品牌")});allProductsData=Array.from(b.values());allBrands=[].concat($jscomp.arrayFromIterable(new Set(Object.values(brandMap)))).sort();brandMultiSelect.setOptions(allBrands.map(function(a){return{value:a,label:a}}).sort(function(a,b){return a.label.localeCompare(b.label)}));filterProductsByBrand();if("longqiao"===currentWarehouse){var c=[].concat($jscomp.arrayFromIterable(new Set(a.map(function(a){return a.customer}).filter(function(a){return a})))).sort();
customerMultiSelect.setOptions(c.map(function(a){return{value:a,label:a}}).sort(function(a,b){return a.label.localeCompare(b.label)}));customerMultiSelect&&customerMultiSelect.reset();brandMultiSelect&&brandMultiSelect.reset()}}catch(d){showRoundedAlert("重新加载品牌和商品选项失败:",d)}}
function fetchRecords(a,b,c){c=void 0===c?{}:c;var d,e,f,g,h,k,l,m,p,q;return $jscomp.asyncExecutePromiseGeneratorProgram(function(n){switch(n.nextAddress){case 1:if(!supabaseClient)throw Error("Supabase客户端未初始化");n.setCatchFinallyBlocks(2);d=1E4;e=[];f=0;g=!0;h=supabaseClient.from(a).select(b.join(","));Object.entries(c).forEach(function(a){var b=$jscomp.makeIterator(a);a=b.next().value;b=b.next().value;Array.isArray(b)?h=h.in(a,b):void 0!==b&&(h="object"===typeof b&&b.gte&&b.lte?h.gte(a,b.gte).lte(a,
b.lte):h.eq(a,b))});case 4:if(!g)return n.return(e);k=h.range(f,f+d-1);return n.yield(k,6);case 6:l=n.yieldResult;m=l.data;if(p=l.error)throw p;m&&0<m.length&&(e=[].concat($jscomp.arrayFromIterable(e),$jscomp.arrayFromIterable(m)));g=m.length===d;f+=d;n.jumpTo(4);break;case 2:throw q=n.enterCatchBlock(),showRoundedAlert("从 "+a+" 获取数据失败:",q),q;}})}
function loadFilterOptions(){var a,b,c,d,e,f,g,h,k,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(m){switch(m.nextAddress){case 1:return m.setCatchFinallyBlocks(2,3),loadingEl.style.display="block",showLoadingOverlay(),a=flatpickrInstance.selectedDates,b=a[0],c=a[1],d=function(a){var b=a.getFullYear(),d=String(a.getMonth()+1).padStart(2,"0");a=String(a.getDate()).padStart(2,"0");return b+"-"+d+"-"+a},startDateStr=d(b),endDateStr=d(c),e="longqiao"===currentWarehouse?"longqiao_records":
"sales_records",f="longqiao"===currentWarehouse?"sale_date product_id product_name sales quantity customer amount cost brand".split(" "):"sale_date product_id product_name warehouse quantity unit_price brand pieces".split(" "),g={sale_date:{gte:startDateStr,lte:endDateStr}},console.time("filter-query"),m.yield(fetchRecords(e,f,g),5);case 5:return salesRecords=m.yieldResult,console.timeEnd("filter-query"),0<salesRecords.length&&(h="longqiao"===currentWarehouse?"sales":"warehouse",allWarehouses=[].concat($jscomp.arrayFromIterable(new Set(salesRecords.map(function(a){return a[h]})))).filter(function(a){return a}).sort()),
brandMap={},0<salesRecords.length&&(k=new Map,salesRecords.forEach(function(a){a.product_id&&!k.has(a.product_id)&&k.set(a.product_id,{product_id:a.product_id,product_name:a.product_name});a.product_id&&a.brand&&(brandMap[a.product_id]=a.brand)}),allProductsData=Array.from(k.values()),allBrands=[].concat($jscomp.arrayFromIterable(new Set(salesRecords.map(function(a){return a.brand})))).filter(function(a){return a}).sort()),"longqiao"===currentWarehouse&&0<salesRecords.length&&(allCustomers=[].concat($jscomp.arrayFromIterable(new Set(salesRecords.map(function(a){return a.customer})))).filter(function(a){return a}).sort()),
warehouseMultiSelect=new MultiSelect(warehouseSelector,warehouseOptions,"longqiao"===currentWarehouse?"销售人员":"仓库"),brandMultiSelect=new MultiSelect(brandSelector,brandOptions,"品牌"),productMultiSelect=new MultiSelect(productSelector,productOptions,"商品"),customerMultiSelect=new MultiSelect(customerSelector,customerOptions,"客户"),customerMultiSelect.setOptions(allCustomers.map(function(a){return{value:a,label:a}}).sort(function(a,b){return a.label.localeCompare(b.label)})),warehouseMultiSelect.setOptions(allWarehouses.map(function(a){return{value:a,
label:a}}).sort(function(a,b){return a.label.localeCompare(b.label)})),brandMultiSelect.setOptions(allBrands.map(function(a){return{value:a,label:a}}).sort(function(a,b){return a.label.localeCompare(b.label)})),productMultiSelect.setOptions(allProductsData.map(function(a){return{value:a.product_id,label:a.product_name}}).sort(function(a,b){return a.label.localeCompare(b.label)})),"longqiao"===currentWarehouse&&1===allBrands.length&&setTimeout(function(){loadData()},0),m.return(Promise.resolve());
case 3:m.enterFinallyBlock();loadingEl.style.display="none";hideLoadingOverlay();m.leaveFinallyBlock(0);break;case 2:return l=m.enterCatchBlock(),showRoundedAlert("筛选选项加载失败: "+l.message,"error"),m.return(Promise.reject(l))}})}
function loadData(){detailSection.classList.contains("visible")&&(detailSection.classList.remove("visible"),document.querySelector("#toggleDetails i").classList.replace("fa-chevron-up","fa-chevron-down"));summaryTable.innerHTML="";detailTable.innerHTML="";clearPieChart();try{var a=salesRecords;"longqiao"===currentWarehouse?0<warehouseMultiSelect.selectedValues.length&&(a=a.filter(function(a){return warehouseMultiSelect.selectedValues.includes(a.sales)})):0<warehouseMultiSelect.selectedValues.length&&
(a=a.filter(function(a){return warehouseMultiSelect.selectedValues.includes(a.warehouse)}));0<brandMultiSelect.selectedValues.length&&(a=a.filter(function(a){return brandMultiSelect.selectedValues.includes(a.brand)}));0<productMultiSelect.selectedValues.length&&(a=a.filter(function(a){return productMultiSelect.selectedValues.includes(a.product_id)}));"longqiao"===currentWarehouse&&customerMultiSelect&&0<customerMultiSelect.selectedValues.length&&(a=a.filter(function(a){return customerMultiSelect.selectedValues.includes(a.customer)}));
calculateSummary(a);renderDetailTable(a,!1)}catch(b){console.error("查询错误详情:",b),loadingEl.innerHTML='\n      <div style="text-align: center; padding: 20px; background: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">\n        <div style="color: #e53e3e; font-size: 3rem; margin-bottom: 1rem;">⚠️</div>\n        <p style="font-size: 1.2rem; margin-bottom: 0.5rem;">数据加载失败</p>\n        <p>'+b.message+"</p>\n      </div>\n    "}}
function renderDetailTable(a,b){b=void 0===b?!1:b;document.getElementById("detailCount").textContent=a&&0!==a.length?"("+a.length+"条)":"(0条数据)";b&&setTimeout(function(){try{console.time("renderDetailTable");var b=detailTable;b.innerHTML="";a&&0<a.length&&a.sort(function(a,b){return new Date(b.sale_date)-new Date(a.sale_date)});a&&0!==a.length?(a.forEach(function(a){var d=document.createElement("tr");if("longqiao"===currentWarehouse){var c=a.amount||0;var g=a.sales||"--";var h=a.cost||0}else c=(a.quantity||
0)*(a.unit_price||0),g=a.warehouse||"--",h=a.unit_price||0;d.innerHTML="\n          <td>"+(a.sale_date||"--")+"</td>\n          <td>"+("longqiao"===currentWarehouse?a.customer||"--":a.product_id||"--")+"</td>\n          <td>"+(a.product_name||"--")+"</td>\n          <td>"+(a.brand||"--")+"</td>\n          <td>"+g+"</td>\n          <td>"+formatNumber(a.quantity||0)+"</td>\n          <td>"+h+"</td>\n          <td>¥"+formatNumber(c)+"</td>\n        ";"longqiao"===currentWarehouse&&(a=(a.amount||0)-(a.cost||
0),d.innerHTML+="<td "+(0>a?'style="color: #e53e3e; font-weight: bold;"':"")+">¥"+formatNumber(a)+"</td>");b.appendChild(d)}),console.timeEnd("renderDetailTable")):b.innerHTML='\n          <tr>\n            <td colspan="'+("longqiao"===currentWarehouse?9:8)+'" style="text-align: center; padding: 30px; color: #6c757d;">\n              <i class="fas fa-database" style="font-size: 3rem; margin-bottom: 1rem; display: block;"></i>\n              未找到匹配的记录\n            </td>\n          </tr>\n        '}catch(d){console.error("渲染详细表格时出错:",
d),detailTable.innerHTML='\n        <tr>\n          <td colspan="'+("longqiao"===currentWarehouse?9:8)+'" style="text-align: center; padding: 30px; color: #e53e3e;">\n            <i class="fas fa-exclamation-triangle" style="font-size: 3rem; margin-bottom: 1rem; display: block;"></i>\n            <p>渲染表格时发生错误</p>\n          </td>\n        </tr>\n      '}},0)}
function getFilteredData(){var a=salesRecords;"longqiao"===currentWarehouse?0<warehouseMultiSelect.selectedValues.length&&(a=a.filter(function(a){return warehouseMultiSelect.selectedValues.includes(a.sales)})):0<warehouseMultiSelect.selectedValues.length&&(a=a.filter(function(a){return warehouseMultiSelect.selectedValues.includes(a.warehouse)}));0<brandMultiSelect.selectedValues.length&&(a=a.filter(function(a){return brandMultiSelect.selectedValues.includes(a.brand)}));0<productMultiSelect.selectedValues.length&&
(a=a.filter(function(a){return productMultiSelect.selectedValues.includes(a.product_id)}));"longqiao"===currentWarehouse&&customerMultiSelect&&0<customerMultiSelect.selectedValues.length&&(a=a.filter(function(a){return customerMultiSelect.selectedValues.includes(a.customer)}));return a}
function showDetailTable(){loadingEl&&(loadingEl.style.display="block",showLoadingOverlay());if(detailSection.classList.contains("visible")){var a=getFilteredData();renderDetailTable(a,!0);setTimeout(function(){loadingEl&&(loadingEl.style.display="none",hideLoadingOverlay())},300)}else loadingEl&&(loadingEl.style.display="none",hideLoadingOverlay())}
function calculateSummary(a){var b=document.getElementById("summaryTable"),c=b.querySelector("thead");c||(c=document.createElement("thead"),b.insertBefore(c,b.firstChild));var d="<tr><th>品牌</th><th>总件数</th><th>总金额</th>";"longqiao"===currentWarehouse&&(d+="<th>总毛利</th><th>费用发放</th>");c.innerHTML=d+"</tr>";var e=b.querySelector("tbody");e||(e=document.createElement("tbody"),b.appendChild(e));if(a&&0!==a.length){var f=0,g=0,h=0,k=0,l=new Set,m=new Set,p=new Map;a.forEach(function(a){a.product_id&&m.add(a.product_id);
a.brand&&l.add(a.brand);if("longqiao"===currentWarehouse){var b=a.amount||0;var d=a.cost||0;0===b?k+=d:(f+=a.quantity||0,g+=b,h+=b-d)}else{d=a.pieces||0;var c=a.unit_price||0;b=(a.quantity||0)*c;f+=d;g+=b;d=c}if("longqiao"!==currentWarehouse||0!==b)c=a.brand||"未知品牌",p.has(c)||p.set(c,{brand:c,total_quantity:0,total_amount:0,total_cost:0,profit:0,free_issue:0}),c=p.get(c),"longqiao"===currentWarehouse?(c.total_quantity+=a.quantity||0,c.total_amount+=b,c.total_cost+=d,c.profit+=b-d):(c.total_quantity+=
a.pieces||0,c.total_amount+=b);"longqiao"===currentWarehouse&&0===b&&(a=a.brand||"未知品牌",p.has(a)||p.set(a,{brand:a,total_quantity:0,total_amount:0,total_cost:0,profit:0,free_issue:0}),p.get(a).free_issue+=d)});b="longqiao"===currentWarehouse&&(1===l.size||1===allBrands.length);var q=1===l.size?Array.from(l)[0]:1===allBrands.length?allBrands[0]:null;if(b&&q){var n=new Map,u=0,r=0,t=0,v=0,w=new Set;a.forEach(function(a){if(a.brand===q&&(a.product_id&&w.add(a.product_id),"longqiao"===currentWarehouse)){var b=
a.amount||0;var c=a.cost||0;var d=a.sales||"未知销售人员";n.has(d)||n.set(d,{sales:d,total_quantity:0,total_amount:0,total_cost:0,profit:0,free_issue:0});d=n.get(d);0===b?(d.free_issue+=c,v+=c):(a=a.quantity||0,d.total_quantity+=a,d.total_amount+=b,d.profit+=b-c,u+=a,r+=b,t+=b-c)}});totalQuantityEl.textContent=formatNumber(u);totalAmountEl.textContent="¥"+formatNumber(r);totalProfitEl.textContent="¥"+formatNumber(t);totalBrandsEl.textContent="¥"+formatNumber(v);totalBrandsEl.style.color="#e53e3e";totalProductsEl.textContent=
formatNumber(w.size);document.querySelectorAll(".stat-card .stat-label")[3].textContent="费用发放";0>=t?totalProfitEl.style.color="#e53e3e":totalProfitEl.style.color="#4361ee";c.innerHTML="<tr><th>销售人员</th><th>总件数</th><th>总金额</th><th>总毛利</th><th>费用发放</th></tr>";a=Array.from(n.values()).sort(function(a,b){return b.total_amount-a.total_amount});e.innerHTML="";a.forEach(function(a){var b=document.createElement("tr"),d=0>a.profit?'style="color: #e53e3e; font-weight: bold;"':"";b.innerHTML="\n          <td>"+
a.sales+"</td>\n          <td>"+formatNumber(a.total_quantity)+"</td>\n          <td>¥"+formatNumber(a.total_amount)+"</td>\n          <td "+d+">¥"+formatNumber(a.profit)+"</td> \n          <td>¥"+formatNumber(a.free_issue)+"</td> \n      ";e.appendChild(b)});0<a.length?renderSalesPieChart(a):clearPieChart()}else totalQuantityEl.textContent=formatNumber(f),totalAmountEl.textContent="¥"+formatNumber(g),c=document.querySelectorAll(".stat-card .stat-label"),"longqiao"===currentWarehouse?(totalBrandsEl.textContent=
"¥"+formatNumber(k),totalBrandsEl.style.color="#e53e3e",c[3].textContent="费用发放",0>=h?totalProfitEl.style.color="#e53e3e":"#4361ee",totalProfitEl.textContent="¥"+formatNumber(h)):(totalBrandsEl.textContent=formatNumber(l.size),totalBrandsEl.style.color="",c[3].textContent="品牌数量"),totalProductsEl.textContent=formatNumber(m.size),c=Array.from(p.values()).sort(function(a,b){return b.total_amount-a.total_amount}),e.innerHTML="",c.forEach(function(a){var b=document.createElement("tr"),d="\n          <td>"+
a.brand+"</td>\n          <td>"+formatNumber(a.total_quantity)+"</td>\n          <td>¥"+formatNumber(a.total_amount)+"</td>\n      ";"longqiao"===currentWarehouse&&(d+="\n              <td "+(0>a.profit?'style="color: #e53e3e; font-weight: bold;"':"")+">¥"+formatNumber(a.profit)+"</td> \n              <td>¥"+formatNumber(a.free_issue)+"</td> \n          ");b.innerHTML=d;e.appendChild(b)}),a&&0<a.length?renderBrandPieChart(c):clearPieChart();setTimeout(function(){syncContainersDimensions()},0)}else totalQuantityEl.textContent=
"0",totalAmountEl.textContent="¥0.00",totalProductsEl.textContent="0",totalBrandsEl.textContent="0","longqiao"===currentWarehouse&&(totalProfitEl.textContent="¥0.00"),e.innerHTML='\n      <tr>\n          <td colspan="'+("longqiao"===currentWarehouse?5:3)+'" style="text-align: center; padding: 30px; color: #6c757d;">\n          <i class="fas fa-chart-bar" style="font-size: 3rem; margin-bottom: 1rem; display: block;"></i>\n          无汇总数据\n        </td>\n      </tr>\n    '}
function renderSalesPieChart(a){var b=document.getElementById("chartContainer");b.innerHTML=0<a.length?'<canvas id="brandChart"></canvas>':'<div class="no-chart-data">无销售人员数据可展示</div>';if(0!==a.length){var c=document.getElementById("brandChart").getContext("2d");c&&(a=new Chart(c,{type:"pie",data:{labels:a.map(function(a){return a.sales}),datasets:[{data:a.map(function(a){return a.total_amount}),backgroundColor:function(a){var b="#4BC0C0 #f54444ff #36A2EB #F15BB5 #FFCE56 #26cd3cff #9966FF #FF9F40 #1982C4 #6A4C93".split(" ");
if(a>b.length)for(var d=b.length;d<a;d++)b.push("#"+Math.floor(16777215*Math.random()).toString(16));return b.slice(0,a)}(a.length),borderWidth:1,borderColor:"#fff",hoverOffset:15,radius:"95%"}]},options:{responsive:!0,maintainAspectRatio:!1,plugins:{legend:{position:"right",labels:{font:{size:12,weight:"bold"},padding:15,usePointStyle:!0,color:"#333"}},title:{display:!0,text:"销售人员销售金额占比",font:{size:18,weight:"bold"},color:"#222",padding:{top:20,bottom:15}},tooltip:{backgroundColor:"rgba(0,0,0,0.8)",
titleFont:{size:14,weight:"bold"},bodyFont:{size:12},callbacks:{label:function(a){var b=a.label||"",d=a.raw||0;a=a.chart.getDatasetMeta(0).total;a=Math.round(d/a*100);return b+": ¥"+formatNumber(d)+" ("+a+"%)"}}},datalabels:{display:!0,formatter:function(a,b){var c=b.chart.getDatasetMeta(0).total;a=Math.round(a/c*100);return 5>a?null:b.chart.data.labels[b.dataIndex]+"\n"+a+"%"},color:"#222",font:{weight:"bold",size:768>=window.innerWidth?8:12},align:"end",anchor:"center",offset:0,clip:!1,textAlign:"center",
padding:2}},animation:{animateRotate:!0,animateScale:!0}},plugins:[ChartDataLabels]}),b.chartInstance=a)}}function syncContainersDimensions(){var a=document.querySelector(".summary-table-container"),b=document.querySelector(".chart-container");a&&b&&(b.style.height=a.offsetHeight+"px",b.chartInstance&&b.chartInstance.resize())}
function renderBrandPieChart(a){var b=document.getElementById("chartContainer");b.innerHTML=0<a.length?'<canvas id="brandChart"></canvas>':'<div class="no-chart-data">无品牌数据可展示</div>';if(0!==a.length){var c=document.getElementById("brandChart").getContext("2d");c&&(a=new Chart(c,{type:"pie",data:{labels:a.map(function(a){return a.brand}),datasets:[{data:a.map(function(a){return a.total_amount}),backgroundColor:function(a){baseColors="longqiao"===currentWarehouse?"#4BC0C0 #f54444ff #36A2EB #F15BB5 #FFCE56 #26cd3cff #9966FF #FF9F40 #1982C4 #6A4C93".split(" "):
"#26cd3cff #FFCE56 #f54444ff #36A2EB #F15BB5 #9966FF #FF9F40 #6A4C93 #4BC0C0 #1982C4".split(" ");if(a>baseColors.length)for(var b=baseColors.length;b<a;b++)baseColors.push("#"+Math.floor(16777215*Math.random()).toString(16));return baseColors.slice(0,a)}(a.length),borderWidth:1,borderColor:"#fff",hoverOffset:15,radius:"95%"}]},options:{responsive:!0,maintainAspectRatio:!1,plugins:{legend:{position:"right",labels:{font:{size:12,weight:"bold"},padding:15,usePointStyle:!0,color:"#333"}},title:{display:!0,
text:"品牌销售金额占比",font:{size:18,weight:"bold"},color:"#222",padding:{top:20,bottom:15}},tooltip:{backgroundColor:"rgba(0,0,0,0.8)",titleFont:{size:14,weight:"bold"},bodyFont:{size:12},callbacks:{label:function(a){var b=a.label||"",c=a.raw||0;a=a.chart.getDatasetMeta(0).total;a=Math.round(c/a*100);return b+": ¥"+formatNumber(c)+" ("+a+"%)"}}},datalabels:{display:!0,formatter:function(a,b){var c=b.chart.getDatasetMeta(0).total;a=Math.round(a/c*100);return 5>a?null:b.chart.data.labels[b.dataIndex]+"\n"+
a+"%"},color:"#222",font:{weight:"bold",size:768>=window.innerWidth?8:12},align:"end",anchor:"center",offset:0,clip:!1,textAlign:"center",padding:2}},animation:{animateRotate:!0,animateScale:!0}},plugins:[ChartDataLabels]}),b.chartInstance=a)}}function clearPieChart(){var a=document.getElementById("chartContainer");a.innerHTML='<div class="no-chart-data">无品牌数据可展示</div>';a.chartInstance&&(a.chartInstance.destroy(),a.chartInstance=null)}
function clearFilters(){warehouseMultiSelect.reset();brandMultiSelect.reset();productMultiSelect.reset();customerMultiSelect&&customerMultiSelect.reset();filterProductsByBrand();clearPieChart();setDefaultDates();loadFilterOptions().then(function(){loadData()})}
function toggleDetailSection(){detailSection.classList.toggle("visible");var a=document.querySelector("#toggleDetails i");detailSection.classList.contains("visible")?(a.classList.replace("fa-chevron-down","fa-chevron-up"),showDetailTable()):(a.classList.replace("fa-chevron-up","fa-chevron-down"),detailTable&&(detailTable.innerHTML=""))}
function showLoadingOverlay(){var a=document.getElementById("loading-overlay");a?a.style.display="flex":(a=document.createElement("div"),a.id="loading-overlay",a.style.cssText="\n      position: fixed;\n      top: 0;\n      left: 0;\n      width: 100%;\n      height: 100%;\n      background-color: rgba(255, 255, 255, 0.2);\n      z-index: 999;\n      display: flex;\n      justify-content: center;\n      align-items: center;\n      backdrop-filter: blur(2px);\n    ",document.body.appendChild(a))}
function hideLoadingOverlay(){var a=document.getElementById("loading-overlay");a&&(a.style.display="none")}
function loadXlsxLibrary(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){try{return a=document.createElement("script"),a.src="https://cdn.bootcdn.net/ajax/libs/xlsx/0.18.5/xlsx.full.min.js",b.return(new Promise(function(b,d){a.onload=function(){return b(window.XLSX)};a.onerror=function(){return d(Error("XLSX库加载失败"))};document.head.appendChild(a)}))}catch(c){return showRoundedAlert("数据导出错误："+c,"error"),b.return(null)}})}
function exportToExcel(){var a,b,c,d,e,f,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(h){switch(h.nextAddress){case 1:if(a=/MicroMessenger/i.test(navigator.userAgent))return showRoundedAlert("微信浏览器不支持此功能，请在浏览器中打开网页导出数据。","warning"),h.return();if("undefined"!==typeof XLSX){h.jumpTo(2);break}h.setCatchFinallyBlocks(3);return h.yield(loadXlsxLibrary(),5);case 5:if(!window.XLSX)throw Error("XLSX库加载失败");h.leaveTryBlock(2);break;case 3:return h.enterCatchBlock(),showRoundedAlert("导出功能暂时不可用。"),
h.return();case 2:try{b=getFilteredData();if(!b||0===b.length)return showRoundedAlert("没有数据可导出","warning"),h.return();c=XLSX.utils.book_new();d=b.map(function(a){if("longqiao"===currentWarehouse){var b=a.amount||0;var c=a.sales||"--";var d=a.cost||0}else b=(a.quantity||0)*(a.unit_price||0),c=a.warehouse||"--",d=a.unit_price||0;var e={"日期":a.sale_date||"--"};"longqiao"===currentWarehouse?e["客户名称"]=a.customer||"--":e["商品ID"]=a.product_id||"--";e["商品名称"]=a.product_name||"--";e["品牌"]=a.brand||"--";"longqiao"===
currentWarehouse?e["销售人员"]=c:e["仓库"]=c;e["销量"]=a.quantity||0;"longqiao"===currentWarehouse?e["成本"]=d:e["单价"]=d;e["金额"]=b;"longqiao"===currentWarehouse&&(e["毛利"]=(a.amount||0)-(a.cost||0));return e});e=XLSX.utils.json_to_sheet(d);XLSX.utils.book_append_sheet(c,e,"销售记录");f="longqiao"===currentWarehouse?"隆桥仓库":"多多买菜";g=f+"_销售记录_"+startDateStr+"_"+endDateStr+".xlsx";XLSX.writeFile(c,g);showRoundedAlert("数据导出成功","success")}catch(k){showRoundedAlert("导出失败: "+k.message,"error")}h.jumpToEnd()}})}
document.addEventListener("DOMContentLoaded",function(){var a;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){if(1==b.nextAddress)return supabaseClient?b.yield(initAuth(),2):(showRoundedAlert("错误: Supabase客户端未正确初始化"),queryBtn.disabled=!0,queryBtn.textContent="系统未初始化",queryBtn.style.background="#e53e3e",queryBtn.style.cursor="not-allowed",loadingEl.innerHTML='<p style="color: #e53e3e; padding: 1rem;">系统初始化失败，请刷新页面</p>',loadingEl.style.display="block",b.return());a=b.yieldResult;document.getElementById("switchWarehouseBtn").addEventListener("click",
switchWarehouse);setupUserMenuEventListeners();if(a)return initializeApp(),b.return();authTabs.forEach(function(a){a.addEventListener("click",function(){var b=a.getAttribute("data-tab");authTabs.forEach(function(a){return a.classList.remove("active")});a.classList.add("active");loginForm.classList.remove("active");registerForm.classList.remove("active");"login"===b?(loginForm.classList.add("active"),loginForm.style.display="block",registerForm.style.display="none"):(registerForm.classList.add("active"),
registerForm.style.display="block",loginForm.style.display="none")})});loginBtn.addEventListener("click",function(){var a,b,e,f,g,h,k,l;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return a=loginEmail.value,b=loginPassword.value,a&&b?c.yield(supabaseClient.auth.signInWithPassword({email:a,password:b}),2):(showRoundedAlert("请输入邮箱和密码","warning"),c.return());e=c.yieldResult;f=e.data;g=e.error;showRoundedAlert("登录成功！","success");if(g)return showRoundedAlert("登录失败: 请检查用户名或密码是否正确！",
"error"),c.return();user=f.user;h=user.email.split("@")[0];k={162004332:"系统管理员",rickyone:"数据管理员",13762405681:"王英",ksf2025:"康师傅",pepsi_cola:"百事可乐",coca_cola:"可口可乐",15096086678:"娟子"};l=k[h]||h;userName.textContent=l;userStatus.style.display="block";authContainer.style.display="none";appContainer.style.display="block";showRoundedAlert("欢迎"+l+"！","success");initializeApp();c.jumpToEnd()})});loginPassword&&loginPassword.addEventListener("keypress",function(a){"Enter"===a.key&&(a.preventDefault(),loginBtn.click())});
registerBtn.addEventListener("click",function(){var a,b,e,f,g,h,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress){a=registerEmail.value;b=registerPassword.value;e=registerPhone.value;if(!a||!b)return showRoundedAlert("请输入邮箱和密码","warning"),c.return();f={email:a,password:b,options:{data:{}}};e&&(f.phone=e);c.setCatchFinallyBlocks(2);return c.yield(supabaseClient.auth.signUp(f),4)}if(2!=c.nextAddress){g=c.yieldResult;if(h=g.error)return showRoundedAlert("注册失败: 该功能被禁止，请与管理员联系！",
"error"),c.return();showRoundedAlert("注册成功! 请检查您的邮箱进行验证","success");authTabs.forEach(function(a){return a.classList.remove("active")});document.querySelector('.auth-tab[data-tab="login"]').classList.add("active");loginForm.classList.add("active");loginForm.style.display="block";registerForm.style.display="none";loginEmail.value=a;return c.leaveTryBlock(0)}k=c.enterCatchBlock();showRoundedAlert("注册异常: "+k.message,"error");c.jumpToEnd()})});forgotPasswordLink.addEventListener("click",function(a){var b,
c,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return a.preventDefault(),b=loginEmail.value,b?d.yield(supabaseClient.auth.resetPasswordForEmail(b,{redirectTo:window.location.href}),2):(showRoundedAlert("请输入您的邮箱","warning"),d.return());c=d.yieldResult;if(f=c.error)return showRoundedAlert("发送重置邮件失败: "+f.message,"error"),d.return();showRoundedAlert("密码重置邮件已发送，请检查您的邮箱","success");d.jumpToEnd()})});b.jumpToEnd()})});
function setupUserMenuEventListeners(){userInfo&&userInfo.addEventListener("click",function(a){a.stopPropagation();userMenu.style.display="block"===userMenu.style.display?"none":"block"});document.addEventListener("click",function(a){userMenu&&"block"===userMenu.style.display&&!userInfo.contains(a.target)&&(userMenu.style.display="none")});logoutBtn&&logoutBtn.addEventListener("click",function(){var a,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return c.setCatchFinallyBlocks(2),
c.yield(supabaseClient.auth.signOut(),4);if(2!=c.nextAddress){a=c.yieldResult;if(b=a.error)return showRoundedAlert("退出登录失败: "+b.message,"error"),c.return();showRoundedAlert("已成功退出登录","success");setTimeout(function(){window.location.reload()},500);return c.leaveTryBlock(0)}c.enterCatchBlock();showRoundedAlert("退出登录时发生错误","error");c.jumpToEnd()})})}
function initializeApp(){(flatpickrInstance=flatpickr(dateRangePicker,{mode:"range",dateFormat:"Y-m-d",static:!0,onChange:function(a){2===a.length&&b()}}))&&setDefaultDates();var a,b=function(){clearTimeout(a);a=setTimeout(function(){loadFilterOptions().then(function(){loadData()}).catch(console.error)},500)};loadFilterOptions().then(function(){queryBtn.addEventListener("click",loadData);clearBtn.addEventListener("click",clearFilters);document.getElementById("toggleDetails").addEventListener("click",
toggleDetailSection);document.getElementById("exportDetails").addEventListener("click",exportToExcel);loadData();console.timeEnd("start")}).catch(function(a){console.error("初始化失败:",a);loadingEl.innerHTML='\n        <div style="text-align: center; padding: 20px; background: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">\n          <div style="color: #e53e3e; font-size: 3rem; margin-bottom: 1rem;">⚠️</div>\n          <p style="font-size: 1.2rem; margin-bottom: 0.5rem;">初始化失败</p>\n          <p>'+
a.message+"</p>\n        </div>\n      ";loadingEl.style.display="block"});document.addEventListener("click",function(a){warehouseSelector.contains(a.target)||warehouseOptions.contains(a.target)||brandSelector.contains(a.target)||brandOptions.contains(a.target)||productSelector.contains(a.target)||productOptions.contains(a.target)||customerSelector.contains(a.target)||customerOptions.contains(a.target)||closeAllDropdowns()},!0);document.querySelectorAll(".select-box").forEach(function(a){a.addEventListener("click",
function(b){var c=b.target.closest(".tag-remove");if(c)if(b.stopPropagation(),b.preventDefault(),c=c.closest(".tag"),b=a.id,c=c.dataset.value,"warehouseSelector"===b){if(b=warehouseOptions.querySelector('input[value="'+c+'"]'))b.checked=!1,c=new Event("change",{bubbles:!0}),b.dispatchEvent(c)}else if("brandSelector"===b){if(b=brandOptions.querySelector('input[value="'+c+'"]'))b.checked=!1,c=new Event("change",{bubbles:!0}),b.dispatchEvent(c)}else if("productSelector"===b){if(b=productOptions.querySelector('input[value="'+
c+'"]'))b.checked=!1,c=new Event("change",{bubbles:!0}),b.dispatchEvent(c)}else"customerSelector"===b&&(b=customerOptions.querySelector('input[value="'+c+'"]'))&&(b.checked=!1,c=new Event("change",{bubbles:!0}),b.dispatchEvent(c))})});window.addEventListener("scroll",function(){closeAllDropdowns()});window.addEventListener("resize",function(){if(currentOpenDropdown){var a=currentOpenDropdown.previousElementSibling;a&&("warehouseSelector"===a.id?warehouseMultiSelect.positionDropdown():"brandSelector"===
a.id?brandMultiSelect.positionDropdown():"productSelector"===a.id?productMultiSelect.positionDropdown():"customerSelector"===a.id&&customerMultiSelect.positionDropdown())}})};