name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Inject secrets
        run: |
          echo "window.SUPABASE_URL='${{ secrets.SUPABASE_URL }}';" > config.js
          echo "window.SUPABASE_KEY='${{ secrets.SUPABASE_KEY }}';" >> config.js
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
